### ISSUE TITLE
Error when update pytz version to 2022.2

### ISSUE THREAD

**Issue by franklindias** [stub42/pytz#80] opened 2022-08-12 14:38 UTC
File "/usr/local/lib/python3.10/site-packages/timezone_field/__init__.py", line 1, in <module>
    from timezone_field.fields import TimeZoneField
  File "/usr/local/lib/python3.10/site-packages/timezone_field/fields.py", line 11, in <module>
    class TimeZoneField(models.Field):
  File "/usr/local/lib/python3.10/site-packages/timezone_field/fields.py", line 41, in TimeZoneField
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
  File "/usr/local/lib/python3.10/site-packages/timezone_field/fields.py", line 41, in <listcomp>
    default_zoneinfo_tzs = [ZoneInfo(tz) for tz in pytz.common_timezones]
  File "/usr/local/lib/python3.10/zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Asia/Hanoi'

**Comment by abhi1693** [comment] 2022-08-12 14:53
Here is a dirty fix

```
cp /usr/local/lib/python3.10/site-packages/tzdata/zoneinfo/Asia/Aden /usr/local/lib/python3.10/site-packages/tzdata/zoneinfo/Asia/Hanoi
```

Credits: https://stackoverflow.com/a/73333310/3193958

**Comment by stub42** [comment] 2022-08-13 00:42
Dupe of https://github.com/stub42/pytz/issues/79

**Closed by stub42** 2022-08-13 00:42 UTC
